import "./globals.css";
import "./custom.css";
import { Inter } from "next/font/google";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <div className="upper">
            <div className="header-wrapper">
              <Header />
            </div>
            <div className="content">
              {children}
            </div>
          </div>
          <div className="lower">
            <div className="footer-wrapper">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
