import "./globals.css";
import "./custom.css";
import localFont from "next/font/local";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";

const myFont = localFont({ src: "./Fonts/oktaneue-ultralight-webfont.woff2" });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="wrapper">
          <div className="upper">
            <div className="header-wrapper">
              <Header />
            </div>
            <div className="content">
              {children}
            </div>
          </div>
          <div className="lower">
            <div className="footer-wrapper">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
